name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make all
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.*
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.4.0
        with:
          file: ./coverage.out
      - uses: haya14busa/action-bumpr@v1
        if: github.ref == 'refs/heads/master'
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist